initializations_to_run:
  start: "2022-02-01T12:00:00"
  end: "2022-02-02T06:00:00"
  freq: "6h"

# save out 1 lam file. you need it for getting conus points.
path_to_static_lam: "lam.nc"

# path to your raw inference files.
# should have naming convention "20180102T000000Z.nc"
# current run_inference.py should save the files out with this naming convention
raw_inference_files_base_path: "inference/transformer/nc"

# as of right now, this is essentialy a flag for if you are using 3km HRRR or not.
# goal is that this will eventually be more robust.
# overall, this flag will tell the script to make x/y dimensions when creating a 2D grid.
curvilinear: False

# level variables in your ds
level_variables:
  - specific_humidity
  - geopotential
  - temperature
  - u_component_of_wind
  - v_component_of_wind
  - vertical_velocity

# levels you want processed in the final ds
levels:
  - 100
  - 150
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
  - 850
  - 925
  - 1000

# vars you want in the final dataset
vars_of_interest:
  - 10m_u_component_of_wind
  - 10m_v_component_of_wind
  - 2m_temperature
  - geopotential_100
  - geopotential_150
  - geopotential_200
  - geopotential_250
  - geopotential_300
  - geopotential_400
  - geopotential_500
  - geopotential_600
  - geopotential_700
  - geopotential_850
  - geopotential_925
  - geopotential_1000
  - specific_humidity_100
  - specific_humidity_150
  - specific_humidity_200
  - specific_humidity_250
  - specific_humidity_300
  - specific_humidity_400
  - specific_humidity_500
  - specific_humidity_600
  - specific_humidity_700
  - specific_humidity_850
  - specific_humidity_925
  - specific_humidity_1000
  - surface_pressure
  - temperature_100
  - temperature_150
  - temperature_200
  - temperature_250
  - temperature_300
  - temperature_400
  - temperature_500
  - temperature_600
  - temperature_700
  - temperature_850
  - temperature_925
  - temperature_1000
  - total_column_water
  - u_component_of_wind_100
  - u_component_of_wind_150
  - u_component_of_wind_200
  - u_component_of_wind_250
  - u_component_of_wind_300
  - u_component_of_wind_400
  - u_component_of_wind_500
  - u_component_of_wind_600
  - u_component_of_wind_700
  - u_component_of_wind_850
  - u_component_of_wind_925
  - u_component_of_wind_1000
  - v_component_of_wind_100
  - v_component_of_wind_150
  - v_component_of_wind_200
  - v_component_of_wind_250
  - v_component_of_wind_300
  - v_component_of_wind_400
  - v_component_of_wind_500
  - v_component_of_wind_600
  - v_component_of_wind_700
  - v_component_of_wind_850
  - v_component_of_wind_925
  - v_component_of_wind_1000
  - vertical_velocity_100
  - vertical_velocity_150
  - vertical_velocity_200
  - vertical_velocity_250
  - vertical_velocity_300
  - vertical_velocity_400
  - vertical_velocity_500
  - vertical_velocity_600
  - vertical_velocity_700
  - vertical_velocity_850
  - vertical_velocity_925
  - vertical_velocity_1000
  - total_precipitation_6hr
